universe = vanilla
log    =  log/project-full-job_$(Cluster)_$(Process).log
error  =  err/project-full-job_$(Cluster)_$(Process).err
#output =  out/project-full-job_$(Cluster)_$(Process).out

executable = ./test_plot.sh
arguments = 2009.csv

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, plot.R, 2009.csv

request_cpus = 1
request_memory = 50GB
request_disk = 25GB

queue 1